server:
  port: 8080
  compression:
    enabled: true
    min-response-size: 1KB
  http2:
    enabled: true
  undertow:
    accesslog:
      enabled: true
      dir: undertow-accesslog
      pattern: '%t %I %r %s %b %D'
  servlet:
    context-path: '/javaverse'

spring:
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:file:../database/Course/H2/course-db;DB_CLOSE_DELAY=10;AUTO_RECONNECT=TRUE;CIPHER=AES;
    username: admin
    password: 'P@ssw0rd 1234'

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.format_sql: true
      hibernate.generate_statistics: true
    open-in-view: false
